curl -o "A BIM-based Building Circularity Assessment tool for the early design stage (LDAC 2021).pdf"                                                                                   https://itc.scix.net/pdfs/w78-2021-paper-049.pdf
curl -o "A Framework for Producing Information Container for linked Document Delivery (ICDD) (LDAC 2021 pres).pdf"                                                                      https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_ManosArgyris.pdf
curl -o "A Linked Building Data Approach to Site Planning and Managing Temporary Construction Items (LDAC 2021 pres).pdf"                                                               https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_Schlachter.pdf
curl -o "A Linked Building Data Approach to Site Planning and Managing Temporary Construction Items (LDAC 2021).pdf"                                                                    https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_99.pdf
curl -o "A Modeling Methodology Towards Digital Twin Development in Smart Factories for the Industry 4.0 Human Augmentation Experiments (LDAC 2021).pdf"                                https://itc.scix.net/pdfs/w78-2021-paper-084.pdf
curl -o "A pilot using a Building Digital Twin for LCA-based human health monitoring (LDAC 2021).pdf"                                                                                   https://itc.scix.net/pdfs/w78-2021-paper-057.pdf
curl -o "An Active Early Warning System for Heavy Construction Vehicle Drivers based on Mixed Reality (LDAC 2021).pdf"                                                                  https://itc.scix.net/pdfs/w78-2021-paper-079.pdf
curl -o "An Audio-based Digital Twin Framework for Autonomous Update on Project Schedule in Civil Infrastructure Construction (LDAC 2021).pdf"                                          https://itc.scix.net/pdfs/w78-2021-paper-006.pdf
curl -o "An Open Data Platform for Early-Stage Building Circularity Assessment (LDAC 2021).pdf"                                                                                         https://itc.scix.net/pdfs/w78-2021-paper-081.pdf
curl -o "An alternative approach to material and EPD mapping in the development of BIM-based LCA and LCC tools (LDAC 2021).pdf"                                                         https://itc.scix.net/pdfs/w78-2021-paper-078.pdf
curl -o "An evaluation of the strict meaning of owl-sameAs in the field of BIM GIS Integration (LDAC 2021 pres).pdf"                                                                    https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_FritzBeck.pdf
curl -o "An evaluation of the strict meaning of owl-sameAs in the field of BIM GIS Integration (LDAC 2021).pdf"                                                                         https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_41.pdf
curl -o "An information-based approach to “Digital Twins” in three case studies (LDAC 2021).pdf"                                                                                        https://itc.scix.net/pdfs/w78-2021-paper-047.pdf
curl -o "Artificial Intelligence in the Construction Industry- Adoption, Benefits and Risks (LDAC 2021).pdf"                                                                            https://itc.scix.net/pdfs/w78-2021-paper-033.pdf
curl -o "BIM and PLM-Based Management of Occupational Health and Safety- A Comparative Literature Review (LDAC 2021).pdf"                                                               https://itc.scix.net/pdfs/w78-2021-paper-089.pdf
curl -o "BPMN-related Ontology for Modeling the Construction Information Delivery of Linked Building Data (LDAC 2021 pres).pdf"                                                         https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_Hagedorn.pdf
curl -o "BPMN-related Ontology for Modeling the Construction Information Delivery of Linked Building Data (LDAC 2021).pdf"                                                              https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_174.pdf
curl -o "Conceptualizing Decentralized Information Containers for Common Data Environments using Linked Data (LDAC 2021).pdf"                                                           https://itc.scix.net/pdfs/w78-2021-paper-059.pdf
curl -o "Conversion of legacy domain models into ontologies for infrastructure maintenance (LDAC 2021 pres).pdf"                                                                        https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_AnneGobels.pdf
curl -o "Conversion of legacy domain models into ontologies for infrastructure maintenance (LDAC 2021).pdf"                                                                             https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_176.pdf
curl -o "Data Patterns for the Organisation of Federated Linked Building Data (LDAC 2021 pres).pptx"                                                                                    https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_Werbrouck.pptx
curl -o "Data Patterns for the Organisation of Federated Linked Building Data (LDAC 2021).pdf"                                                                                          https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_116.pdf
curl -o "Design rationale documentation and exchange in the Danish AEC industry (LDAC 2021).pdf"                                                                                        https://itc.scix.net/pdfs/w78-2021-paper-055.pdf
curl -o "Developing a standardised approach of Asset Lifecycle Information Modelling for Semantic Digital Twins in the built environment (LDAC 2021).pdf"                               https://itc.scix.net/pdfs/w78-2021-paper-095.pdf
curl -o "Development of a Guideline for Standard Models in the Context of Building Information Modeling (LDAC 2021).pdf"                                                                https://itc.scix.net/pdfs/w78-2021-paper-025.pdf
curl -o "Development of a conceptual digital deconstruction platform with integrated Reversible BIM to aid decision making and facilitate a circular economy (LDAC 2021).pdf"           https://itc.scix.net/pdfs/w78-2021-paper-090.pdf
curl -o "Digital Twin Development for Stack Effect Mitigation (LDAC 2021).pdf"                                                                                                          https://itc.scix.net/pdfs/w78-2021-paper-010.pdf
curl -o "Digital Twins to BIM Object Library – A Top-Down Modeling Approach (LDAC 2021).pdf"                                                                                            https://itc.scix.net/pdfs/w78-2021-paper-066.pdf
#curl -o "Dynamic BIM model conversion as inference-based ontology alignment (LDAC 2021 pres).pdf"                                                                                      https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_Bourreau.pptx: 404
curl -o "Dynamic BIM model conversion as inference-based ontology alignment (LDAC 2021).pdf"                                                                                            https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_65.pdf
curl -o "Enabling Digital Twins with Advanced Visualization and Contextualization of Sensor Data with BIM and Web Technologies (LDAC 2021).pdf"                                         https://itc.scix.net/pdfs/w78-2021-paper-085.pdf
curl -o "Enabling Multi-scale Energy Modelling through a Linked-Data Approach (LDAC 2021 pres).pdf"                                                                                     https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_JamesODonnell.pdf
curl -o "Environmental Impact Assessment of Buildings Based on Building Information Modelling (LDAC 2021).pdf"                                                                          https://itc.scix.net/pdfs/w78-2021-paper-046.pdf
curl -o "Exploring the utility of AR for quality inspections in timber-frame house production – A case study from Småland, Sweden (LDAC 2021).pdf"                                      https://itc.scix.net/pdfs/w78-2021-paper-031.pdf
curl -o "Fire risk assessment contributions for the EU building logbook structure – Case study of Braga’s city block (LDAC 2021).pdf"                                                   https://itc.scix.net/pdfs/w78-2021-paper-053.pdf
curl -o "How Virtual Reality is used when involving healthcare staff in the design process (LDAC 2021).pdf"                                                                             https://itc.scix.net/pdfs/w78-2021-paper-042.pdf
curl -o "Identification of common data environment functions during construction phase of BIM-based projects (LDAC 2021).pdf"                                                           https://itc.scix.net/pdfs/w78-2021-paper-026.pdf
curl -o "Initiating and designing an emerging multi-platform ecosystem for the circular economy in the built environment- An empirical case study (LDAC 2021).pdf"                      https://itc.scix.net/pdfs/w78-2021-paper-060.pdf
curl -o "Integrating Virtual Reality During the Architectural Design Process- a Survey to Identify Practitioner Needs (LDAC 2021).pdf"                                                  https://itc.scix.net/pdfs/w78-2021-paper-054.pdf
curl -o "Integration of Geotechnical Investigation and Quality Control processes in the BIM methodology for Infrastructures (LDAC 2021 pres).pdf"                                       https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_GloriaCalleja.pdf
curl -o "Interoperability between BIM and GIS through open data standards- An overview of current literature (LDAC 2021 pres).pptx"                                                     https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_EyosiasGuyo.pptx
curl -o "Interoperability between BIM and GIS through open data standards- An overview of current literature (LDAC 2021).pdf"                                                           https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_171.pdf
curl -o "Linked Data in Asset Management (Why Asset Data Must Be FAIR- The SIDO Case) (LDAC 2021 pres).pdf"                                                                             https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_JanVoskuil.pdf
curl -o "Multi-disciplinary learning from OpenBIM (LDAC 2021).pdf"                                                                                                                      https://itc.scix.net/pdfs/w78-2021-paper-070.pdf
curl -o "Ontological approach for LOD-sensitive BIM-data management (LDAC 2021 pres).pptx"                                                                                              https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_Karlapudi.pptx
curl -o "Ontological approach for LOD-sensitive BIM-data management (LDAC 2021).pdf"                                                                                                    https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_131.pdf
curl -o "Ontology-based Building Energy System Commissioning and Monitoring (LDAC 2021 pres).pdf"                                                                                       https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_Pruvost.pdf
curl -o "Ontology-based anamnesis and diagnosis of natural stone damage for retrofitting (LDAC 2021 pres).pdf"                                                                          https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_HamdanAlHakam.pdf
curl -o "Ontology-based anamnesis and diagnosis of natural stone damage for retrofitting (LDAC 2021).pdf"                                                                               https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_172.pdf
curl -o "Popularizing DGNB in the Danish construction industry- A field study of the industry via a qualitative comparative analysis (LDAC 2021).pdf"                                   https://itc.scix.net/pdfs/w78-2021-paper-064.pdf
curl -o "Post-Urban Mining Automation and Digitalisation for a Closed-Loop Circular Construction (LDAC 2021).pdf"                                                                       https://itc.scix.net/pdfs/w78-2021-paper-035.pdf
curl -o "Potential of digital tools for BIM-based risk management (LDAC 2021).pdf"                                                                                                      https://itc.scix.net/pdfs/w78-2021-paper-007.pdf
curl -o "Queries on Semantic Building Digital Twins for Robot Navigation (LDAC 2021 pres).pptx"                                                                                         https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_Koning.pptx
curl -o "Queries on Semantic Building Digital Twins for Robot Navigation (LDAC 2021).pdf"                                                                                               https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_78.pdf
curl -o "Real-Time Building Performance Monitoring using Semantic Digital Twins (LDAC 2021 pres).pptx"                                                                                  https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_Donkers.pptx
curl -o "Real-Time Building Performance Monitoring using Semantic Digital Twins (LDAC 2021).pdf"                                                                                        https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_38.pdf
curl -o "Reviewing Technique for Order Preference by Similarity to Ideal Solution (TOPSIS) to support decision support system development in the Construction Industry (LDAC 2021).pdf" https://itc.scix.net/pdfs/w78-2021-paper-080.pdf
curl -o "Similarity Evaluation of the Predeveloped MVD Concepts for Improving Reusability of Existing MVDs (LDAC 2021).pdf"                                                             https://itc.scix.net/pdfs/w78-2021-paper-011.pdf
curl -o "Software Tools Supporting Advanced Design Requirements for Digital Twins (LDAC 2021).pdf"                                                                                      https://itc.scix.net/pdfs/w78-2021-paper-022.pdf
curl -o "TUBES System Ontology- Digitalization of building service systems (LDAC 2021 pres).pdf"                                                                                        https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_Pauen.pdf
curl -o "TUBES System Ontology- Digitalization of building service systems (LDAC 2021).pdf"                                                                                             https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_115.pdf
curl -o "The Digital Twin in the AEC-FM Industry- a literature review (LDAC 2021).pdf"                                                                                                  https://itc.scix.net/pdfs/w78-2021-paper-012.pdf
curl -o "The Golden Day- Using Common Data Environments to Improve the Response Time in the Management of Change Orders (LDAC 2021).pdf"                                                https://itc.scix.net/pdfs/w78-2021-paper-075.pdf
curl -o "Toward a Reference Architecture Framework for the development of interoperable construction digital platforms in Europe (LDAC 2021).pdf"                                       https://itc.scix.net/pdfs/w78-2021-paper-039.pdf
curl -o "Towards a Taxonomy of Built Asset Lifecycle Information Coupling (LDAC 2021).pdf"                                                                                              https://itc.scix.net/pdfs/w78-2021-paper-041.pdf
curl -o "Towards automatic construction of photorealistic BIM window elements from single-picture input (LDAC 2021).pdf"                                                                https://itc.scix.net/pdfs/w78-2021-paper-034.pdf
curl -o "Virtual Reality Design Quality-Check Tool for Engineering Projects (LDAC 2021).pdf"                                                                                            https://itc.scix.net/pdfs/w78-2021-paper-091.pdf
curl -o "bcfOWL- A BIM collaboration ontology (LDAC 2021 pres).pdf"                                                                                                                     https://linkedbuildingdata.net/ldac2021/files/presentations/LDAC2021_OliverSchulz.pdf
curl -o "bcfOWL- A BIM collaboration ontology (LDAC 2021).pdf"                                                                                                                          https://linkedbuildingdata.net/ldac2021/files/papers/CIB_W78_2021_paper_122.pdf                    
